"""Weekly project briefs."""

PROJECTS = {
    1: {
        "title": "Production-grade ReAct agent over a small CRM",
        "summary": "Build a ReAct-style agent that answers questions over a small CRM dataset using three tools. Add iteration capping, logging, and an evaluation harness.",
        "tools": ["lookup_customer(id)", "search_tickets(query)", "calculate(expr)"],
        "deliverables": [
            "agent.py with the ReAct loop, iteration cap, and structured logging",
            "tools.py with the three tools and a small fixture CSV",
            "evals/test_set.json with 30 questions and gold answers",
            "evals/run.py that runs the eval and reports accuracy plus average iterations",
            "README.md with run instructions reproducible in under 5 minutes",
        ],
        "rubric_extra": "Bonus 5 points for a clean failure analysis of the lowest-scoring 5 questions.",
    },
    2: {
        "title": "Planner-Worker-Critic team in LangGraph",
        "summary": "Build a three-agent team that researches a topic and produces a 600-word brief with citations.",
        "tools": ["web_search(query)", "fetch_url(url)", "extract_quotes(text)"],
        "deliverables": [
            "LangGraph state schema (typed)",
            "Three node implementations with explicit system prompts",
            "Checkpoint store integration (file-based for the prototype)",
            "Eval on 10 topics with rubric scores",
            "README plus run trace for one full topic",
        ],
        "rubric_extra": "Bonus 5 points for adding a 'reject' edge that the Critic uses with structured reasons.",
    },
    3: {
        "title": "FastMCP server with OAuth-protected tool",
        "summary": "Build and deploy a FastMCP server with three tools, one of which requires OAuth 2.1 with PKCE.",
        "tools": ["calendar.list_events(date_range)", "wiki.search(query)", "notes.append(text)"],
        "deliverables": [
            "server.py with all three tools and structured error returns",
            "OAuth integration for calendar with consent flow",
            "Working stdio and HTTP transports",
            "MCP inspector validation screenshot",
            "Test suite with 15 tool-call assertions",
            "Docker image for the HTTP server",
        ],
        "rubric_extra": "Bonus 5 points for adding token-refresh handling that the agent never sees.",
    },
    4: {
        "title": "DSPy program with MIPRO optimization beating a hand-crafted baseline",
        "summary": "Pick a 7-class text classification task. Build a hand-crafted CO-STAR prompt baseline. Then build a DSPy program and optimize with MIPRO. Beat the baseline by at least 5 percentage points.",
        "tools": ["OpenAI or Anthropic API", "DSPy with MIPRO optimizer", "Eval harness from the lab"],
        "deliverables": [
            "Hand-crafted baseline with documented CO-STAR fields",
            "DSPy Signature and Module implementation",
            "MIPRO optimization config and training trace",
            "Eval comparison table with confidence intervals",
            "One-page writeup on what MIPRO discovered that the human missed",
        ],
        "rubric_extra": "Bonus 5 points for ablating instruction-only vs demos-only vs both.",
    },
    5: {
        "title": "Three-way fine-tuning comparison on a domain instruction set",
        "summary": "Pick a small base model (1-3B). Fine-tune with full FT, LoRA, and qLoRA on a domain instruction set (300-500 examples). Compare on quality, GPU hours, peak memory, and inference latency.",
        "tools": ["Hugging Face TRL", "PEFT library", "bitsandbytes for qLoRA"],
        "deliverables": [
            "Three training scripts with identical hyperparameters where applicable",
            "Training curves for all three runs",
            "Eval on 50 held-out instructions with human or rubric scoring",
            "Comparison table on the four metrics",
            "Recommendation paragraph: when would you pick each method",
        ],
        "rubric_extra": "Bonus 5 points for a fourth run with a different LoRA rank to show rank sensitivity.",
    },
    6: {
        "title": "PPO on a non-trivial gridworld with reward shaping",
        "summary": "Design a 10x10 gridworld with obstacles, a moving goal, and a partial-observability window. Implement PPO with reward shaping that improves convergence by at least 2x over an unshaped baseline.",
        "tools": ["PyTorch", "Custom env (no Gym required)"],
        "deliverables": [
            "env.py with the world and partial observation function",
            "ppo.py implementing PPO from scratch (no external RL lib)",
            "Two training runs: unshaped vs shaped reward",
            "Plots of return, KL, and entropy",
            "Writeup explaining the shaping signal and why it works",
        ],
        "rubric_extra": "Bonus 5 points for sweeping the clip parameter across {0.1, 0.2, 0.3}.",
    },
    7: {
        "title": "DPO vs GRPO head-to-head on an LLM",
        "summary": "Fine-tune the same 1-3B base model with DPO and GRPO on the same preference data. Compare on alignment quality, training cost, and the failure modes each method exhibits.",
        "tools": ["TRL with DPO and GRPO support", "Preference dataset (your choice)"],
        "deliverables": [
            "Two training scripts with shared base config",
            "Training curves for both",
            "Held-out preference eval (win rate against base)",
            "Failure mode catalog: 10 examples where each method fails",
            "Recommendation: when to pick each",
        ],
        "rubric_extra": "Bonus 5 points for adding a PPO baseline using a reward model.",
    },
    8: {
        "title": "Production serving stack: vLLM + Ray Serve + Airflow",
        "summary": "Take a fine-tuned model from week 5. Serve it with vLLM behind Ray Serve. Wire the training-eval-deploy loop into an Airflow DAG. Demonstrate a canary rollout with rollback.",
        "tools": ["vLLM", "Ray Serve", "Airflow", "OpenTelemetry"],
        "deliverables": [
            "Ray Serve deployment spec",
            "Airflow DAG with five tasks (extract, train, eval, gate, deploy)",
            "Canary rollout config with metric-based promotion",
            "Load test report: P50/P95 latency and throughput",
            "Rollback demonstration log",
        ],
        "rubric_extra": "Bonus 5 points for adding a shadow-traffic stage before canary.",
    },
    9: {
        "title": "A2A protocol between two heterogeneous agents",
        "summary": "Build one agent in Google ADK and one in a custom Python framework. Connect them over A2A with mTLS. Both must discover each other through a registry.",
        "tools": ["Google ADK", "Custom Python A2A client", "Local mTLS CA"],
        "deliverables": [
            "Both agent implementations",
            "Registry service (small Flask app is fine)",
            "mTLS setup with cert rotation script",
            "End-to-end trace with discovery, capability negotiation, task exchange",
            "Threat model: what does mTLS plus capability scopes protect against?",
        ],
        "rubric_extra": "Bonus 5 points for adding a third agent that the first two discover and use.",
    },
    10: {
        "title": "Three architectural patterns on the same task",
        "summary": "Pick a non-trivial task. Implement it three ways: Router, Orchestrator-Workers, Evaluator-Optimizer. Run on the same eval set. Pick a winner and defend.",
        "tools": ["LangGraph or Google ADK", "Eval harness from week 4"],
        "deliverables": [
            "Three implementations with shared eval interface",
            "Cost, latency, and quality numbers for each",
            "Architectural diagram for each",
            "One-page writeup defending the winner",
            "Note on when the loser pattern would actually win",
        ],
        "rubric_extra": "Bonus 5 points for adding a fourth pattern of your choice.",
    },
    11: {
        "title": "Agentic RAG with trajectory-trained student",
        "summary": "Build a multi-hop agentic RAG over a 50K-document corpus with three backends (vector, BM25, SQL). Capture trajectories. Train a smaller student model on successful trajectories. Compare teacher and student on the same eval set.",
        "tools": ["Vector store (FAISS or pgvector)", "BM25 index", "SQL warehouse", "Microsoft Agent Lightning"],
        "deliverables": [
            "Agentic RAG implementation with router and HyDE",
            "Eval on 100 multi-hop questions",
            "Trajectory capture pipeline",
            "Student fine-tuning script",
            "Teacher-vs-student comparison on eval, latency, cost",
        ],
        "rubric_extra": "Bonus 5 points for measuring per-backend hit rates and routing accuracy.",
    },
    12: {
        "title": "Capstone: end-to-end agentic application",
        "summary": "Build a working agentic application that solves a real problem you care about. Apply at least four patterns from the course. Include evals, observability, and a deployment story.",
        "tools": ["Your choice", "Must use one MCP server", "Must use one fine-tuned model"],
        "deliverables": [
            "Working application with README reproducible in under 30 minutes",
            "Eval suite with at least 50 examples",
            "Observability hookups (logs, traces, metrics)",
            "10-slide presentation deck",
            "Written reflection: one decision you would make differently",
        ],
        "rubric_extra": "Bonus up to 10 points for novelty and depth, judged by faculty.",
    },
}
