"""Quiz bank per week. 12 MCQs + 3 short answers each."""

QUIZZES = {
    1: {
        "mcq": [
            ("Which of the following best distinguishes an agent from a static pipeline?",
             ["Use of an LLM", "A persistent goal across turns with tool selection",
              "Higher token cost", "Use of vector retrieval"], 1,
             "Agency requires a persistent goal and the ability to select actions based on observations."),
            ("In the escalation ladder, which rung should you try first?",
             ["Multi-agent system", "Tool-using single agent",
              "Static pipeline", "Retrieval augmented call"], 2,
             "Always start at the lowest rung that could plausibly solve the problem."),
            ("Which is NOT a typical agent failure mode?",
             ["Prompt drift", "Context overflow", "Tool runaway loops",
              "Deterministic latency"], 3,
             "Latency variability is a symptom; deterministic latency is rare in agentic systems."),
            ("Why is iteration capping non-negotiable in production agents?",
             ["LLM APIs require it", "It speeds up training",
              "It prevents runaway loops from exhausting tokens or causing harm",
              "It improves accuracy"], 2,
             "Without a cap, a confused agent can loop indefinitely, burning budget or causing damage."),
            ("Which boundary protects against credential leakage in tool outputs?",
             ["The data boundary", "The credential boundary",
              "The action boundary", "The presentation boundary"], 1,
             "Credentials should never be stored in the prompt or exposed in tool output."),
            ("Which is the BEST first defense against prompt injection via fetched web content?",
             ["Switch to GPT-4 from GPT-3.5", "Increase max iterations",
              "Sandbox the agent and treat fetched content as untrusted data",
              "Use a smaller temperature"], 2,
             "Treat all external content as untrusted data, not as instructions."),
            ("On the autonomy ladder, where should a new production agent typically start?",
             ["Autonomous with audit", "Approve-each-step",
              "Suggest-only", "Approve-batches"], 2,
             "Start low and ratchet up as the agent proves reliable."),
            ("The Ray cluster object store is best described as:",
             ["A persistent disk store",
              "An in-memory zero-copy store shared across workers on the same node",
              "A relational database",
              "A queue for task scheduling"], 1,
             "Same-node workers share immutable objects without serialization cost."),
            ("Which of the following is a property of an agentic loop?",
             ["Termination only when a user cancels",
              "Observation, plan, act, update with a defined termination condition",
              "Always exactly one tool call per turn",
              "No memory across iterations"], 1,
             "The loop has a defined structure and an explicit termination."),
            ("Tool-use maximalism means:",
             ["Giving one agent every tool you have",
              "Forbidding tools entirely",
              "One tool per agent",
              "Auto-generating tools from API specs"], 0,
             "It is the design choice to centralize tools in one well-trained agent."),
            ("What is the recommended max-iteration cap for an n8n agent prototype?",
             ["Unlimited", "1", "5", "100"], 2,
             "Five is a sensible prototype default; raise only with monitoring in place."),
            ("Which is NOT part of the four-axis evaluation rubric introduced later in the course?",
             ["Quality", "Cost", "Color", "Latency"], 2,
             "The four axes are quality, cost, latency, safety."),
        ],
        "short": [
            "Define agency in one sentence and give an example that is not an agent under your definition.",
            "Describe the escalation ladder and pick a real task where you stop at rung two.",
            "Sketch a concrete defense-in-depth strategy for an agent that browses the public web.",
        ],
    },
    2: {
        "mcq": [
            ("Which decomposition style is observable from the start?",
             ["Bottom-up", "Top-down", "Random", "Lazy"], 1,
             "Top-down emits the full tree first, which makes the structure visible."),
            ("Scratchpad memory should typically be cleared:",
             ["Never", "On every response", "Once per day", "On user request"], 1,
             "Scratchpad memory is per-turn."),
            ("Agentic RAG differs from static RAG primarily in:",
             ["Using vector stores", "Using more documents",
              "Letting the agent decide when and what to retrieve",
              "Using larger models"], 2,
             "Retrieval becomes a decision the agent makes, not a fixed prelude."),
            ("Which game-theoretic setting describes agents with private rewards?",
             ["Cooperative", "Mixed-motive", "Competitive", "None of the above"], 2,
             "Private rewards make the setting competitive by default."),
            ("Which is the standard reason to track P95 latency separately from P50?",
             ["P95 is required by law", "Tail latencies determine user-perceived performance",
              "P50 includes warmup", "They are the same"], 1,
             "Means hide the tail; P95 catches what users feel."),
            ("Which agent acts as the verifier in a planner-worker-critic structure?",
             ["Planner", "Worker", "Critic", "Router"], 2,
             "The critic verifies; the planner plans; the worker executes."),
            ("Semantic memory is typically backed by:",
             ["A relational table", "A queue", "A vector store with embeddings",
              "A flat text file"], 2,
             "Semantic memory uses similarity search on embeddings."),
            ("Which evaluation axis specifically catches jailbreak vulnerabilities?",
             ["Quality", "Cost", "Latency", "Safety"], 3,
             "Safety covers refusal correctness, leak rate, and jailbreak resistance."),
            ("In Google ADK, the message bus enables:",
             ["Persistent storage", "Inter-agent communication and turn coordination",
              "GPU scheduling", "Token counting"], 1,
             "ADK uses a message bus for coordination between agents."),
            ("Which is a typical advantage of LangGraph state schemas?",
             ["Higher throughput", "Type-safe state transitions and resumability",
              "Free GPU access", "Lower token usage"], 1,
             "Typed state and checkpointing are the core benefits."),
            ("A 'mixed-motive' agent system requires:",
             ["A single shared reward", "Explicit protocol design around incentive structures",
              "Banning private rewards", "Equal token budgets"], 1,
             "Mixed-motive needs explicit incentive design."),
            ("Production evaluation should run:",
             ["Once at launch", "On every release plus continuous monitoring",
              "Only when bugs reported", "Annually"], 1,
             "Continuous evaluation catches drift early."),
        ],
        "short": [
            "Differentiate scratchpad, session, and semantic memory using a customer-service example.",
            "Sketch a planner-worker-critic flow for SEC filing summarization.",
            "Why does collapsing all three memory stores into one fail in production?",
        ],
    },
    3: {
        "mcq": [
            ("MCP capability negotiation happens at:",
             ["Every tool call", "Server boot only", "Session startup", "Never"], 2,
             "Capabilities are negotiated once per session."),
            ("FastMCP generates tool schemas from:",
             ["Manual JSON files", "Python type hints and docstrings",
              "OpenAPI specs", "GraphQL"], 1,
             "Decorator-style Python with typed signatures."),
            ("The 'tool-use maximalist' pattern fails most often when:",
             ["The model is small", "The tool catalog crosses the model's selection bandwidth",
              "Tools are async", "Tools return JSON"], 1,
             "Confusion grows with tool count past a model-specific limit."),
            ("Which auth pattern fits user-delegated tool access?",
             ["Service accounts only", "OAuth 2.1 with PKCE",
              "Plain API key", "Anonymous"], 1,
             "OAuth 2.1 with PKCE is the standard for delegated access."),
            ("Idempotency keys are typically issued by:",
             ["The server", "The client", "The DNS provider", "The model"], 1,
             "Clients issue keys so retries are recognized."),
            ("Which MCP transport is best for local subprocess tools?",
             ["WebSocket", "HTTP", "stdio", "gRPC"], 2,
             "stdio is the default for in-process tool servers."),
            ("A structured error return helps the agent:",
             ["Reduce token cost", "Reason about retry vs giveup",
              "Compress context", "Improve grammar"], 1,
             "The agent can decide intelligently based on error type."),
            ("Which is the BEST argument name for a tool that takes a date?",
             ["d", "date", "start_date_iso8601", "DATE"], 2,
             "Argument names are the prompt; specificity reduces ambiguity."),
            ("MCP resources differ from tools because they:",
             ["Run on GPU", "Are read-only data sources",
              "Cost money", "Cannot be cached"], 1,
             "Resources are read-only; tools are actions."),
            ("Per-tool scopes are preferred over per-server scopes because:",
             ["They are easier to write", "They limit blast radius of a leaked token",
              "Servers do not exist", "OAuth requires them"], 1,
             "Smaller scopes mean a smaller leak."),
            ("Which is a common mistake in tool docstrings?",
             ["Being too long", "Being too short and ambiguous",
              "Using complete sentences", "Including examples"], 1,
             "Short, vague docstrings produce wrong tool calls."),
            ("OAuth 2.1 PKCE protects against:",
             ["Server outages", "Authorization code interception",
              "Token theft via XSS", "Replay attacks"], 1,
             "PKCE prevents code interception in public clients."),
        ],
        "short": [
            "Write a FastMCP tool function with strong type hints and a clear docstring for a calendar lookup.",
            "Compare stdio versus HTTP MCP transports on latency, security, and operational complexity.",
            "Design an idempotency strategy for a 'send_email' tool exposed via MCP.",
        ],
    },
    4: {
        "mcq": [
            ("In CO-STAR, the 'S' stands for:",
             ["Schema", "Source", "Style", "Stop"], 2, "Style."),
            ("Few-shot prompting recency bias means:",
             ["Models forget old examples",
              "Later examples are weighted more heavily",
              "Recent users get better answers",
              "Refusal must come first"], 1,
             "Models attend more to recent examples."),
            ("DSPy's Signature defines:",
             ["The model", "Inputs and outputs",
              "The tokenizer", "The retrieval store"], 1,
             "A Signature is the input-output contract."),
            ("Which DSPy optimizer is fastest?",
             ["MIPRO", "COPRO", "BootstrapFinetune", "All equal"], 1,
             "COPRO is coordinate ascent; MIPRO is heavier Bayesian search."),
            ("Hallucination mitigation via self-consistency works by:",
             ["Asking the model once",
              "Sampling N answers and voting",
              "Using a larger model",
              "Lowering temperature to zero"], 1,
             "Self-consistency samples and votes."),
            ("GEPA is best described as:",
             ["A reward model", "Evolutionary prompt optimization with reflection",
              "A tokenizer", "A retrieval library"], 1,
             "Genetic plus reflective critique."),
            ("TextGrad treats text as:",
             ["A graph", "A tensor with critic-LLM gradients",
              "A list", "A queue"], 1,
             "TextGrad uses critic LLMs as gradient signals."),
            ("Which is NOT a CO-STAR field?",
             ["Audience", "Tone", "Reward", "Response format"], 2,
             "Reward is from RL, not CO-STAR."),
            ("Few-shot example diversity matters more than:",
             ["Example length", "Example count",
              "Example formatting", "Example punctuation"], 1,
             "Three diverse examples beat seven similar ones."),
            ("MIPRO jointly optimizes:",
             ["Weights and tokenizer", "Instructions and demonstrations",
              "Model and temperature", "Prompts and rewards"], 1,
             "MIPRO does Bayesian joint search."),
            ("Structured output via tool-call schema reduces hallucination by:",
             ["Refusing invalid JSON outputs",
              "Increasing temperature",
              "Removing the LLM",
              "Adding noise"], 0,
             "Schema-constrained decoding rejects malformed outputs."),
            ("ORPO unifies:",
             ["Pretraining and instruction tuning",
              "Preference optimization with reference-free training",
              "RAG and fine-tuning",
              "Inference and training"], 1,
             "ORPO blends preference learning with SFT-like signal."),
        ],
        "short": [
            "Write a CO-STAR prompt for an internal HR FAQ bot.",
            "Walk through a DSPy MIPRO optimization for a 3-class classifier.",
            "When does TextGrad outperform DSPy, and where does it struggle?",
        ],
    },
    5: {
        "mcq": [
            ("Chinchilla scaling suggests roughly how many training tokens per parameter?",
             ["1", "5", "20", "100"], 2, "Roughly 20 tokens per parameter."),
            ("LoRA trains:",
             ["The full base model", "Only the low-rank A and B matrices",
              "Only embeddings", "Only attention weights"], 1,
             "Frozen base, trainable low-rank update."),
            ("Typical LoRA rank values in practice:",
             ["1 to 2", "4 to 64", "256 to 1024", "4096+"], 1,
             "4 to 64 is the practical range."),
            ("qLoRA quantizes the base model to:",
             ["8-bit", "4-bit NF4 with double quantization",
              "2-bit", "1-bit binary"], 1,
             "NF4 with double quantization."),
            ("InfoNCE loss requires:",
             ["Only positives", "Anchor, positive, batch of negatives",
              "Triplets with margin", "Cluster assignments"], 1,
             "Softmax over similarities with one positive."),
            ("Soft prompting trains:",
             ["Full layers", "A small trainable embedding prefix",
              "The tokenizer", "Quantization codebook"], 1,
             "A small prefix of trainable embeddings."),
            ("Steering vectors are applied:",
             ["During training only", "At inference time as activation edits",
              "To the tokenizer", "To the dataset"], 1,
             "Activation steering at inference."),
            ("Which is a typical LoRA target module set for transformer LLMs?",
             ["Embedding only", "MLP only",
              "Q, V, O projections", "All layer norms"], 2,
             "Q, V, O (and sometimes K, MLP) are common targets."),
            ("Higher LoRA rank helps most when:",
             ["Only style changes", "Domain semantics change",
              "Tokenizer is unchanged", "Dataset is small"], 1,
             "Bigger semantic shifts benefit from more capacity."),
            ("Triplet loss is sensitive primarily to:",
             ["Batch size", "Triplet mining strategy",
              "Optimizer choice", "Model size"], 1,
             "Easy triplets give no signal; hard triplets dominate."),
            ("SimCLR positives are typically generated from:",
             ["Manual labeling", "Augmentations of the same example",
              "Class clusters", "Reward models"], 1,
             "SimCLR uses augmentation-derived positives."),
            ("qLoRA accuracy on long-context tasks tends to:",
             ["Improve substantially", "Remain identical",
              "Degrade more than expected", "Match 8-bit exactly"], 2,
             "Quantization errors compound at long context."),
        ],
        "short": [
            "Given a 1B parameter budget and 20B tokens, justify Chinchilla compliance or deviation.",
            "Choose LoRA rank, alpha, and target modules for a domain-adaptation task on a 7B model.",
            "Sketch a hard-negative mining strategy for InfoNCE training on a code search corpus.",
        ],
    },
    6: {
        "mcq": [
            ("In an MDP for an LLM token policy, the 'state' is typically:",
             ["A single token", "The current context window",
              "The vocabulary", "The reward model"], 1,
             "Context window represents state."),
            ("The advantage function is defined as:",
             ["Q(s,a) only", "V(s) only",
              "Q(s,a) - V(s)", "V(s) - Q(s,a)"], 2,
             "A = Q - V."),
            ("PPO's clip parameter typically defaults to:",
             ["0.01", "0.2", "0.5", "1.0"], 1, "0.2 is the canonical value."),
            ("DPO requires:",
             ["A reward model", "Preference pairs",
              "An environment simulator", "Tool definitions"], 1,
             "DPO uses preference pairs directly."),
            ("GRPO's main memory advantage comes from:",
             ["Dropping the policy network", "Dropping the value network",
              "Using INT8", "Using gradient checkpointing only"], 1,
             "Group advantage removes need for value head."),
            ("The KL penalty in PPO-style RLHF prevents:",
             ["Slow training", "Policy drift away from the reference model",
              "Reward overflow", "Token leakage"], 1,
             "KL keeps the policy near the reference."),
            ("Reward hacking is most associated with:",
             ["Insufficient compute", "Mis-specified reward signals",
              "Slow data loading", "Tokenization errors"], 1,
             "Models maximize the proxy, not the intent."),
            ("Helpful, Honest, Harmless is:",
             ["A model name", "An alignment rubric",
              "A scaling law", "A loss function"], 1,
             "Three-axis alignment rubric."),
            ("TRPO uses a trust region defined by:",
             ["L2 norm", "KL divergence",
              "Entropy bound", "Token count"], 1,
             "KL divergence trust region."),
            ("Policy gradient is unbiased but:",
             ["Slow to compute", "High variance",
              "Always wrong", "Requires a reward model"], 1,
             "Variance reduction is the central engineering problem."),
            ("In GRPO, typical group sizes are:",
             ["1", "4 to 8", "100", "1000+"], 1, "4-8 in practice."),
            ("DPO's beta parameter controls:",
             ["Learning rate", "How strongly to follow preferences",
              "Batch size", "Reward scaling"], 1,
             "Lower beta follows preferences more aggressively."),
        ],
        "short": [
            "Derive the PPO clipped objective from the policy gradient theorem.",
            "Compare DPO and PPO on data needs, compute, and stability.",
            "Design a reward function where helpful and harmless directly conflict, and resolve it.",
        ],
    },
    7: {
        "mcq": [
            ("SRP applied to agents means:",
             ["Maximum tools per agent",
              "Each agent has one well-defined responsibility",
              "All agents share state",
              "One agent per user"], 1,
             "One responsibility per agent."),
            ("A facade agent's purpose is:",
             ["Cosmetic UI", "Wrapping a noisy sub-system with a clean tool surface",
              "Performance benchmarking", "Memory caching"], 1,
             "Facades hide complexity."),
            ("Epistemic uncertainty can be reduced by:",
             ["More data", "Higher temperature",
              "Smaller model", "Tokenization changes"], 0,
             "Knowledge gaps shrink with data."),
            ("Aleatoric uncertainty is reduced by:",
             ["More data", "Better calibration only",
              "Bigger models", "Vector databases"], 1,
             "Randomness is irreducible; calibrate it."),
            ("Idempotency keys are essential for:",
             ["Read tools", "Write tools that may be retried",
              "Tokenizers", "Embeddings"], 1,
             "Writes must be safe under retry."),
            ("PPO on LLMs without KL penalty typically:",
             ["Trains stably", "Drifts off the manifold and hacks reward",
              "Improves coherence", "Reduces cost"], 1,
             "KL is the guardrail."),
            ("Typical LR for PPO on a 7B LLM:",
             ["1e-3", "1e-4", "1e-6 to 5e-6", "1e-8"], 2,
             "RLHF LRs are very small."),
            ("DPO typical beta range:",
             ["0.01-0.05", "0.05-0.2", "0.5-1.0", ">1.0"], 1, "0.05-0.2."),
            ("Tool-maximalist vs multi-agent is decided by:",
             ["Personal taste", "Empirical measurement on the task",
              "Framework support", "Tool count alone"], 1,
             "Measure on your task."),
            ("GRPO group size tradeoff:",
             ["Larger is always better", "Larger groups give better estimates but cost more",
              "Smaller is always better", "Group size does not matter"], 1,
             "Bigger groups, better estimates, more cost."),
            ("Reward scaling for PPO typically targets:",
             ["Mean reward of 0.5", "Median advantage of order 1",
              "Total reward sum of 100", "Token count"], 1,
             "Scale so advantages are O(1)."),
            ("Which is NOT a typical training instability sign?",
             ["KL spike", "Reward collapse",
              "Entropy collapse", "Steady token speed"], 3,
             "Steady token speed is expected; the others are red flags."),
        ],
        "short": [
            "Diagnose a PPO run where KL spikes at step 200. List three remedies.",
            "Pick a system where tool-maximalist clearly beats multi-agent. Justify with measurable signals.",
            "Explain epistemic vs aleatoric using a fraud detection example.",
        ],
    },
    8: {
        "mcq": [
            ("Data parallel training shares:",
             ["Different data, same gradients", "Same model, sharded data, all-reduce gradients",
              "Sharded model, same data", "Sharded model, sharded data only"], 1,
             "Standard data-parallel definition."),
            ("Tensor parallel splits:",
             ["Layers across devices", "Each matrix multiply across devices",
              "Batches across devices", "Optimizer state only"], 1,
             "Splits within each linear op."),
            ("Pipeline parallel splits:",
             ["Each matrix multiply", "Model layers across devices with micro-batches",
              "Optimizer state", "Tokens across devices"], 1,
             "Layer groups stream micro-batches."),
            ("Ray actors are best for:",
             ["Stateless computations", "Stateful long-lived workers",
              "Pure functions only", "Token streaming"], 1,
             "Actors hold state."),
            ("Ray Tune's ASHA scheduler is:",
             ["Bayesian", "Async successive halving",
              "Genetic", "Manual"], 1,
             "ASHA = Async Successive Halving."),
            ("vLLM's PagedAttention is analogous to:",
             ["GPU caches", "OS virtual memory paging",
              "Disk RAID", "TCP windows"], 1,
             "Paged KV-cache like virtual memory."),
            ("Ray Serve provides:",
             ["Training only", "Routing, autoscaling, and traffic shaping",
              "Tokenization", "Storage"], 1,
             "Serving infrastructure."),
            ("Airflow DAGs encode:",
             ["Model weights", "Task dependencies for orchestration",
              "Vector embeddings", "Reward signals"], 1,
             "DAGs are dependency graphs."),
            ("Continuous batching benefits LLM serving by:",
             ["Reducing temperature", "Allowing dynamic merging of requests with different lengths",
              "Forcing fixed batch sizes", "Reducing model size"], 1,
             "Dynamic merging boosts throughput."),
            ("A metric gate in MLOps does:",
             ["Counts metrics", "Blocks promotion if eval drops below threshold",
              "Logs to S3", "Sends notifications"], 1,
             "Gates protect production from regressions."),
            ("Which parallelism is needed when a single GPU cannot hold one layer?",
             ["Data parallel", "Tensor parallel",
              "Pipeline parallel", "Replica scaling"], 1,
             "Tensor parallel splits within layers."),
            ("Ray object store is best for:",
             ["Persistent storage", "Sharing immutable data zero-copy across same-node workers",
              "Streaming logs", "Token generation"], 1,
             "Same-node zero-copy."),
        ],
        "short": [
            "Choose a parallelism strategy for fine-tuning a 70B model on 16 H100s. Justify.",
            "Design a Ray Serve autoscaling policy for chat workload with bursty traffic.",
            "Write the five-task Airflow DAG that drives the bootcamp lab pipeline.",
        ],
    },
    9: {
        "mcq": [
            ("A2A is primarily for:",
             ["Agent-to-tool", "Agent-to-agent",
              "Agent-to-user", "Tool-to-tool"], 1, "A2A = agent-to-agent."),
            ("MCP is primarily for:",
             ["Agent-to-agent", "Agent-to-tool",
              "User-to-tool", "User-to-agent"], 1, "MCP = agent-to-tool."),
            ("An Agent Card lists:",
             ["Only price", "Capabilities, cost, latency, contact, auth requirements",
              "Source code", "Training data"], 1, "Self-description manifest."),
            ("Nanda proposes:",
             ["Centralized identity", "A federated agent registry",
              "Closed proprietary system", "DNS replacement only"], 1,
             "Federated registry model."),
            ("mTLS at the transport layer satisfies:",
             ["AuthZ alone", "AuthN; AuthZ still needed at message layer",
              "Both AuthN and AuthZ", "Neither"], 1,
             "mTLS = authentication only."),
            ("Voting-based cooperation is best when:",
             ["Generation is hard, verification weak", "Verifier is weaker than proposers",
              "All agents trust each other", "Single agent suffices"], 1,
             "Voting helps when no single verifier is strong enough."),
            ("Debate-based cooperation is best when:",
             ["Answers are hard to generate but easy to verify",
              "Answers are easy to generate but hard to verify",
              "Only one agent is available",
              "Real-time latency is critical"], 1,
             "Debate exposes errors a single generator misses."),
            ("Role-based cooperation fails when:",
             ["All agents have the same role", "The task shifts and roles need to renegotiate",
              "Bandwidth is unlimited", "Reward is shared"], 1,
             "Fixed roles are brittle."),
            ("Capability negotiation in A2A happens:",
             ["At every message", "At session start",
              "Never", "Only on failure"], 1,
             "Handshake at session start."),
            ("Per-message scoped capabilities limit:",
             ["Throughput", "Blast radius of a compromised agent",
              "Latency", "Token cost"], 1,
             "Scopes limit damage."),
            ("Discovery is analogous to:",
             ["HTTP", "DNS for hostnames",
              "TCP", "JSON"], 1,
             "Discovery resolves agent identities."),
            ("Logging every hop with structured fields enables:",
             ["Lower cost", "Auditability and post-incident debugging",
              "Better grammar", "Faster training"], 1,
             "Audit trails matter."),
        ],
        "short": [
            "Author an Agent Card for a market-research agent that charges $0.20 per task and runs in 30 seconds P95.",
            "Compare Nanda and Cisco Agency on trust model, governance, and operational fit.",
            "Sketch an mTLS rotation strategy that does not require downtime.",
        ],
    },
    10: {
        "mcq": [
            ("The router pattern is typically used:",
             ["For high-stakes generation", "To direct input to one of N specialized agents",
              "As a verifier", "To merge results"], 1,
             "Routing dispatches to specialists."),
            ("Fan-out / fan-in is appropriate when:",
             ["Strict serial order required", "Parallel proposals or comparisons help",
              "Single-tool use suffices", "Latency must be minimized"], 1,
             "Parallel evaluation."),
            ("Orchestrator-workers separates:",
             ["Training from inference", "Planning from execution",
              "Storage from compute", "Tokens from embeddings"], 1,
             "Planner plans; workers execute."),
            ("Evaluator-optimizer's stop condition is typically:",
             ["Random", "Quality threshold or max iterations",
              "User timeout only", "Token budget only"], 1,
             "Either quality or iteration cap."),
            ("The autonomy ladder recommends starting at:",
             ["Autonomous", "Approve-batch",
              "Suggest-only", "Approve-each"], 2,
             "Always start low."),
            ("Sandbox-then-act adds:",
             ["No overhead", "One extra call per action",
              "Two extra calls", "Removes calls"], 1,
             "One sandbox check before each real action."),
            ("Cache-and-skip primarily controls:",
             ["Latency only", "Cost via reusing tool results by argument",
              "Safety", "Memory"], 1,
             "Cost optimization via caching."),
            ("Long-running task pattern requires:",
             ["No checkpointing", "Checkpointing and resume support",
              "Single-threaded execution", "GPU only"], 1,
             "Async work needs durable state."),
            ("The agentic OSI model has roughly how many layers?",
             ["3", "4", "6", "7"], 2, "Six layers in the bootcamp's model."),
            ("Supervisor-with-veto means:",
             ["Supervisor approves everything", "A small fast model can veto the main agent",
              "Vetoes are random", "No supervision"], 1,
             "Fast veto without full re-planning."),
            ("Ruthless simplification means:",
             ["Add components freely", "Default to deleting components and simplifying",
              "Use more frameworks", "Add layers"], 1,
             "Delete before adding."),
            ("Anti-pattern 'god agent' is:",
             ["A well-scoped agent", "A single agent doing everything; untestable",
              "A backup agent", "A debugging agent"], 1,
             "Untestable, unobservable, fragile."),
        ],
        "short": [
            "Pick a recent system you built and apply ruthless simplification. List five deletions.",
            "Compare router and fan-out/fan-in on a code-review task. Which wins and why?",
            "Map a real failure on the agentic OSI model and explain how the model helped you debug it.",
        ],
    },
    11: {
        "mcq": [
            ("HyDE retrieves against:",
             ["Original query embedding", "Embedding of a hypothetical answer",
              "Random vectors", "Keyword index"], 1,
             "Embed hypothesis, then retrieve."),
            ("Multi-hop RAG's main challenge is:",
             ["Embedding speed", "Intermediate evaluation of partial answers",
              "Index size", "Tokenization"], 1,
             "Knowing when to query again."),
            ("Predetermined decomposition is best when:",
             ["Path is unpredictable", "Path is largely known in advance",
              "Latency is unimportant", "Agents have private rewards"], 1,
             "Predictable paths fit predetermined plans."),
            ("Adaptive decomposition is best when:",
             ["Path depends on prior results", "All sub-queries are known up front",
              "Single retrieval suffices", "Latency must be minimized"], 0,
             "Each step informs the next."),
            ("Multi-source routing typically uses:",
             ["One source only", "A small classifier that selects backends",
              "Random selection", "User preference only"], 1,
             "Classifier-based routing."),
            ("Trajectory-based training requires capturing:",
             ["Only outputs", "State, action, observation, reward per step",
              "Loss values only", "Token IDs only"], 1,
             "Full trajectory tuples."),
            ("Successful trajectories are typically used for:",
             ["Pretraining only", "Distilling a smaller student agent",
              "Reward modeling only", "Quantization"], 1,
             "Distill teacher to student."),
            ("Microsoft Agent Lightning provides:",
             ["A search engine", "A framework for trajectory capture and training",
              "An IDE", "A tokenizer"], 1,
             "Trajectory training framework."),
            ("When does HyDE NOT help?",
             ["Out-of-domain queries", "Queries where the embedder already handles the gap well",
              "Multi-hop questions", "Code search"], 1,
             "If the gap is small, HyDE adds cost without gain."),
            ("Vector + BM25 hybrid retrieval typically beats:",
             ["Pure vector for keyword-heavy queries", "BM25 alone for semantic queries",
              "Both alone on many real corpora", "All of the above"], 3,
             "Hybrid wins on most corpora."),
            ("Trajectory data for training must be:",
             ["Unfiltered", "Filtered for success and balanced by task type",
              "Random sample", "Only the longest runs"], 1,
             "Quality and balance matter."),
            ("Student model selection should consider:",
             ["Maximum size", "The smallest size that meets quality bar at target cost",
              "Random choice", "Same as teacher"], 1,
             "Right-size the student."),
        ],
        "short": [
            "Design a multi-hop RAG flow for a question that spans two SEC filings and one news article.",
            "Pick a query class where HyDE clearly helps and one where it does not. Justify.",
            "Sketch the trajectory-capture schema for a code-generation agent.",
        ],
    },
    12: {
        "mcq": [
            ("The RAG-vs-fine-tuning ladder starts with:",
             ["Full fine-tune", "LoRA", "RAG", "RLHF"], 2,
             "RAG first; fine-tune for behavior change."),
            ("RLVR replaces the reward model with:",
             ["A larger LLM", "A programmatic verifier",
              "A human judge", "A random reward"], 1,
             "Verifier as reward."),
            ("Regression suite for fine-tuned models exists to:",
             ["Replace eval", "Catch loss of base capabilities",
              "Improve speed", "Reduce cost"], 1,
             "Detect skill loss."),
            ("MARL's 'centralized training, decentralized execution' means:",
             ["Train together, run alone", "Train alone, run together",
              "Both together", "Both alone"], 0,
             "Standard CTDE pattern."),
            ("Reward shaping in MARL solves:",
             ["Tokenizer issues", "Credit assignment across agents",
              "Latency", "Storage"], 1,
             "Who deserves credit for shared success."),
            ("RLVR is best for tasks where:",
             ["Reward is subjective", "Reward is programmatically checkable",
              "No reward exists", "Human-only judgment"], 1,
             "Verifier-friendly tasks."),
            ("Capstone presentation length:",
             ["5 min", "10 min", "15 min + 5 Q&A", "60 min"], 2,
             "Standard presentation slot."),
            ("Harm test in fine-tuned model evaluation should:",
             ["Be skipped", "Explicitly probe suppressed bad behaviors",
              "Run on random inputs", "Be optional"], 1,
             "Probe what fine-tuning was meant to suppress."),
            ("Hybrid RAG + fine-tune is appropriate when:",
             ["Either alone suffices", "Neither alone meets the bar",
              "Cost is unlimited", "Tooling forces it"], 1,
             "Combine when individual approaches fall short."),
            ("Drift checks for fine-tuned models should run:",
             ["Once", "Continuously as data distribution evolves",
              "Only on failure", "Annually"], 1,
             "Continuous monitoring."),
            ("MARL beats single-agent when:",
             ["Always", "Agents have genuinely different observation spaces",
              "Compute is scarce", "Latency must be lowest"], 1,
             "Real specialization matters."),
            ("Peer review uses:",
             ["No rubric", "A structured written rubric",
              "Only verbal feedback", "Random scoring"], 1,
             "Structured rubric."),
        ],
        "short": [
            "Walk an example task up the RAG-vs-fine-tune ladder, justifying each rung.",
            "Sketch an RLVR setup for an SQL-generation agent. Define the verifier precisely.",
            "Design a five-test harm suite for a customer-facing fine-tuned model.",
        ],
    },
}
