"""Weekly project briefs for the RAG bootcamp."""

PROJECTS = {
    1: {
        "title": "Production-grade simple RAG with baseline eval",
        "summary": "Build a 200-line RAG over a 2000-document corpus. Use FAISS, a small embedder, and a generator. Include a 30-question eval set with gold answers and an automated eval harness.",
        "tools": ["FAISS", "bge-small or sentence-transformers", "An LLM API"],
        "deliverables": [
            "rag.py with load, chunk, embed, index, retrieve, generate",
            "evals/test_set.json with 30 questions",
            "evals/run.py that computes recall@8 and answer F1",
            "README with reproducible setup",
            "One-page failure analysis on the 5 worst answers",
        ],
        "rubric_extra": "Bonus 5 points for measuring per-query latency and reporting P50 and P95.",
    },
    2: {
        "title": "Contrastive embedder fine-tuning",
        "summary": "Fine-tune a sentence embedder on a domain corpus with InfoNCE. Mine hard negatives. Evaluate retrieval improvement.",
        "tools": ["sentence-transformers", "Domain corpus shipped with the lab"],
        "deliverables": [
            "Training script with InfoNCE and configurable temperature",
            "Hard-negative miner",
            "Eval on STS-B and the domain retrieval set",
            "Anisotropy measurement before and after",
            "Recommendation on temperature for this corpus",
        ],
        "rubric_extra": "Bonus 5 points for ablating temperature across {0.05, 0.1, 0.2}.",
    },
    3: {
        "title": "Four chunking strategies head to head",
        "summary": "Implement fixed-size, semantic, late, and contextual chunking on the same corpus. Compare retrieval recall@10 and end-to-end answer quality.",
        "tools": ["Embedder with long-context support", "An LLM API for contextual summaries"],
        "deliverables": [
            "Four chunker implementations with shared interface",
            "Indexed corpus for each",
            "100-query eval set with gold answers",
            "Comparison table with recall@10 and answer F1",
            "Recommendation paragraph keyed to corpus characteristics",
        ],
        "rubric_extra": "Bonus 5 points for adding a hierarchical (mother-child) strategy as a fifth option.",
    },
    4: {
        "title": "Four-stage retrieval funnel end to end",
        "summary": "Build the four-stage funnel (sparse + dense, Matryoshka prune, ColBERT, cross-encoder) on a 100K-document corpus. Tune candidate counts. Beat dense-only baseline by at least 5 points recall@5.",
        "tools": ["Pyserini (BM25)", "Matryoshka embedder", "RAGatouille (ColBERT)", "sentence-transformers cross-encoder"],
        "deliverables": [
            "Full funnel implementation",
            "Dense-only baseline",
            "Eval on a 200-question set",
            "Latency breakdown per stage",
            "Tuning writeup with the rationale for each candidate count",
        ],
        "rubric_extra": "Bonus 5 points for measuring marginal contribution of each stage via ablation.",
    },
    5: {
        "title": "Multimodal RAG with CLIP and BLIP-2",
        "summary": "Build a multimodal RAG over a corpus of 5000 images and their captions. Support text-to-image, image-to-image, and image-to-text retrieval. Use BLIP-2 for VQA on retrieved images.",
        "tools": ["open_clip", "Lavis (BLIP-2)", "FAISS"],
        "deliverables": [
            "Unified embedding index for images and text",
            "Three retrieval modes",
            "VQA pipeline using BLIP-2",
            "Eval on 30 multimodal questions",
            "Note on what BLIP-2 gets wrong",
        ],
        "rubric_extra": "Bonus 5 points for comparing CLIP and BLIP-2 image embeddings as the retrieval backbone.",
    },
    6: {
        "title": "DSPy beats hand-crafted prompt",
        "summary": "Pick a 7-class classification task. Write a hand-crafted CO-STAR baseline. Optimize with DSPy MIPRO. Beat the baseline by at least 5 percentage points.",
        "tools": ["DSPy", "OpenAI or Anthropic API"],
        "deliverables": [
            "CO-STAR baseline prompt with documented fields",
            "DSPy Signature and Module",
            "MIPRO optimization trace",
            "Eval comparison with confidence intervals",
            "Writeup on what MIPRO discovered",
        ],
        "rubric_extra": "Bonus 5 points for adding a GEPA run and comparing all three.",
    },
    7: {
        "title": "RAPTOR vs GraphRAG on multi-hop questions",
        "summary": "Build a RAPTOR pipeline and a GraphRAG pipeline on the same 5K-document corpus. Compare on 50 multi-hop questions for quality, ingestion cost, and query latency.",
        "tools": ["RAPTOR reference impl", "Neo4j or Memgraph", "GraphRAG reference impl"],
        "deliverables": [
            "Both pipelines built and indexed",
            "50-question multi-hop eval set",
            "Cost breakdown for ingestion and query",
            "Comparison table",
            "Recommendation by corpus type",
        ],
        "rubric_extra": "Bonus 5 points for adding LightRAG as a third comparison.",
    },
    8: {
        "title": "Production guardrail and grounding pipeline",
        "summary": "Build a four-stage guardrail pipeline (syntax, PII, toxicity, intent) and an NLI-based response grounding checker. Measure throughput and false-positive rates. Hit a 3-second P95 budget end to end.",
        "tools": ["Presidio (PII)", "DeBERTa-large-mnli (NLI)", "Toxicity model"],
        "deliverables": [
            "Pipeline implementation with early exits",
            "1000-input throughput test",
            "False-positive and false-negative analysis",
            "P95 latency report",
            "Tuning recommendation with explicit threshold values",
        ],
        "rubric_extra": "Bonus 5 points for adding a prompt-injection adversarial test suite.",
    },
    9: {
        "title": "Enterprise enrichment: factoids, HyDE, semantic cache",
        "summary": "Add factoid and QA-pair derivative artifacts to a RAG corpus. Add HyDE on the query side. Build a semantic cache layer. Measure cumulative cost reduction and quality impact.",
        "tools": ["LLM API for factoid generation", "Existing RAG stack", "Cache vector store"],
        "deliverables": [
            "Enriched corpus with factoids and QA pairs",
            "HyDE pipeline integrated",
            "Semantic cache with tuned threshold",
            "Cost report: before vs after",
            "Quality report on the same eval set",
        ],
        "rubric_extra": "Bonus 5 points for adding hard-negative mining and quantifying embedder improvement.",
    },
    10: {
        "title": "Agentic RAG + Text-to-SQL on a real schema",
        "summary": "Build an agentic RAG that includes a Text-to-SQL path for structured questions. Use MCP for tool exposure. Compare to static RAG on a mixed test set.",
        "tools": ["Google ADK or LangGraph", "FastMCP", "A sample SQL database"],
        "deliverables": [
            "Agentic loop with structured and unstructured tools",
            "Text-to-SQL pipeline with schema retrieval",
            "MCP tool server",
            "Eval on 100 mixed questions",
            "Cost-quality comparison vs static RAG",
        ],
        "rubric_extra": "Bonus 5 points for adding a small CTE library and measuring SQL complexity reduction.",
    },
    11: {
        "title": "Text-to-SQL fine-tuning with LoRA and GRPO",
        "summary": "Fine-tune a small base model on a Text-to-SQL task. First with LoRA SFT. Then add a GRPO pass using execution accuracy as the verifier. Compare to few-shot baseline.",
        "tools": ["TRL with GRPO", "PEFT", "Spider or Bird dataset"],
        "deliverables": [
            "Few-shot baseline",
            "LoRA SFT checkpoint and eval",
            "GRPO checkpoint and eval",
            "Comparison table on exact match and execution accuracy",
            "Cost-time analysis",
        ],
        "rubric_extra": "Bonus 5 points for analyzing where GRPO helps vs hurts at the query-type level.",
    },
    12: {
        "title": "Capstone: full RAG eval and improvement plan",
        "summary": "Take the RAG you have built across the bootcamp. Run a comprehensive eval (Ragas, LLM-as-judge, RGB-style robustness). Identify the biggest weakness. Implement one targeted improvement. Re-evaluate.",
        "tools": ["Ragas", "LLM judge", "Your full RAG stack"],
        "deliverables": [
            "Full eval report on baseline",
            "Identified biggest weakness with evidence",
            "One targeted improvement implemented",
            "Re-evaluation report",
            "Written reflection on what surprised you",
        ],
        "rubric_extra": "Bonus up to 10 points for novelty and depth of the improvement.",
    },
}
