"""Quiz bank for RAG bootcamp. 12 MCQs + 3 short answers each week."""

QUIZZES = {
    1: {
        "mcq": [
            ("BM25 still beats dense retrieval primarily on:",
             ["Multi-hop questions", "Keyword and rare-term queries",
              "Conversational queries", "Image queries"], 1,
             "Keyword and rare-term queries play to BM25's exact-match strength."),
            ("In scaled dot-product attention, the scaling by sqrt(d) is used to:",
             ["Reduce memory", "Keep softmax in a usable range as d grows",
              "Improve convergence speed only", "Enable causal masking"], 1,
             "Without scaling, softmax saturates and gradients vanish in high d."),
            ("Encoder models (BERT family) are best for:",
             ["Open-ended generation", "Embeddings and classification",
              "Image segmentation", "Audio synthesis"], 1,
             "Encoders produce strong contextual representations."),
            ("HNSW is best described as:",
             ["A quantization scheme", "A graph-based ANN index",
              "A sparse retriever", "A reranker"], 1,
             "Hierarchical Navigable Small Worlds is a graph ANN."),
            ("Approximate nearest neighbor search trades:",
             ["Memory for latency", "Recall for speed",
              "Precision for memory only", "Throughput for cost"], 1,
             "ANN gives up a small amount of recall for orders of magnitude speed."),
            ("Which is NOT among the five numbers to benchmark on a vector DB?",
             ["Index build time", "RAM footprint",
              "Color depth", "Query throughput"], 2,
             "Color depth is irrelevant."),
            ("Self-attention computes attention weights using:",
             ["Q and K only", "Q, K, V projections",
              "Just embeddings", "Convolutions"], 1,
             "Q, K to compute weights; V is what gets weighted."),
            ("Multi-head attention runs attention:",
             ["Sequentially", "In parallel h times and concatenates",
              "Only on the first layer", "Only at inference"], 1,
             "Parallel heads then concat."),
            ("Product quantization helps mainly with:",
             ["Recall", "Memory footprint at billion scale",
              "Build time only", "Latency only"], 1,
             "PQ compresses the vectors themselves."),
            ("A typical embedder dimension in 2026 ranges roughly:",
             ["8 to 16", "64 to 128", "384 to 1024", "10000+"], 2,
             "Production embedders sit in this range."),
            ("Decoder-only models like GPT predict:",
             ["Masked tokens", "The next token from left context",
              "Token positions", "Class labels"], 1,
             "Autoregressive next-token prediction."),
            ("IVF (inverted file) indexes are best when:",
             ["RAM is unlimited", "Memory pressure is high",
              "Recall must be perfect", "Embeddings are 4-dimensional"], 1,
             "IVF is memory-friendly at scale."),
        ],
        "short": [
            "Explain why dense retrieval helps when query and document share meaning but no words.",
            "Sketch a benchmark plan for choosing between HNSW and IVF on a 50M-vector corpus.",
            "Pick a downstream task and choose between encoder, decoder, and encoder-decoder. Justify.",
        ],
    },
    2: {
        "mcq": [
            ("In high-dimensional unit balls, volume concentrates:",
             ["At the center", "Near the surface",
              "Uniformly", "On the axes"], 1,
             "Volume concentrates near the surface."),
            ("Random unit vectors in 768D are typically:",
             ["Aligned", "Almost orthogonal",
              "Opposite", "Identical"], 1,
             "Random vectors are nearly orthogonal in high d."),
            ("Anisotropy in BERT embeddings means:",
             ["High variance across dims", "Embeddings cluster in a narrow cone",
              "Embeddings have zero norm", "Tokens are uniformly distributed"], 1,
             "Pretrained embeddings cluster in a narrow cone."),
            ("Whitening of embeddings primarily:",
             ["Adds noise", "Removes anisotropy via decorrelation and scaling",
              "Increases dimension", "Reduces vocabulary"], 1,
             "Whitening decorrelates and standardizes."),
            ("InfoNCE loss uses negatives drawn from:",
             ["The whole corpus", "The current batch",
              "Random noise", "The validation set"], 1,
             "In-batch negatives."),
            ("Low temperature in contrastive softmax:",
             ["Flattens the distribution", "Sharpens the distribution; harder negatives",
              "Eliminates negatives", "Increases bias"], 1,
             "Low temp sharpens; emphasizes hardest negatives."),
            ("Production InfoNCE temperatures typically fall:",
             ["0.001", "0.05 to 0.2",
              "1.0", "10 or higher"], 1,
             "Common range is 0.05-0.2."),
            ("BERT pretraining objective is:",
             ["Next sentence prediction only", "Masked language modeling (+ NSP)",
              "Image classification", "Token classification"], 1,
             "MLM is the primary objective."),
            ("SimCSE uses:",
             ["Random pairs", "Dropout as the only augmentation for positives",
              "BPE merges", "Image augmentations"], 1,
             "Same sentence through dropout produces positive pair."),
            ("Triplet loss requires:",
             ["No negatives", "Anchor, positive, negative, margin",
              "Batch of all positives", "Hard negatives only"], 1,
             "Triplet = (a, p, n) with margin."),
            ("Distance concentration in high d means:",
             ["Distances diverge", "Min and max distances become similar",
              "Distances are zero", "Distances are infinite"], 1,
             "Ratio of max to min distance approaches 1."),
            ("Cosine similarity is preferred over Euclidean when:",
             ["Vectors are small", "Direction matters more than magnitude",
              "Always", "Never"], 1,
             "Cosine ignores magnitude, captures direction."),
        ],
        "short": [
            "Explain anisotropy and propose two ways to correct it.",
            "Implement InfoNCE in PyTorch pseudocode and identify where temperature lives.",
            "When does Triplet loss outperform InfoNCE, and why is this rare?",
        ],
    },
    3: {
        "mcq": [
            ("Chunking's central tradeoff is:",
             ["Speed vs cost", "Precision vs context",
              "Memory vs throughput", "Recall vs precision only"], 1,
             "Small=precise, large=context."),
            ("Fixed-size chunking is best when:",
             ["Documents are heterogeneous", "Documents are homogeneous and cheap to process",
              "All queries are multi-hop", "Embeddings are anisotropic"], 1,
             "Fixed-size is cheap and predictable for uniform corpora."),
            ("Semantic chunking splits where:",
             ["Token count exceeds limit", "Adjacent sentence similarity drops",
              "Paragraphs end", "Headers appear"], 1,
             "Embedding-similarity-based boundaries."),
            ("Late chunking requires:",
             ["A vector DB", "An embedder that supports long context",
              "A graph DB", "A reward model"], 1,
             "Embed whole doc first; needs long-context embedder."),
            ("Contextual chunking prepends:",
             ["Random tokens", "An LLM-generated summary of surrounding context",
              "The full document", "A timestamp"], 1,
             "Anthropic's approach: short context summary."),
            ("Anthropic reported what improvement from contextual retrieval?",
             ["5%", "Roughly 35%", "100%", "0%"], 1,
             "About 35% average retrieval improvement."),
            ("Hierarchical retrieval uses:",
             ["One chunk size", "Two granularities: child for match, mother for context",
              "Many random sizes", "Token-only chunking"], 1,
             "Mother and child chunks."),
            ("A 200-token chunk typically:",
             ["Has high context, low precision", "Has high precision, low context",
              "Is impossible", "Wastes memory"], 1,
             "Small chunks are precise but context-poor."),
            ("Overlap in fixed-size chunking is usually:",
             ["0%", "10-20%",
              "50%", "100%"], 1,
             "10-20% is common."),
            ("Late chunking preserves what?",
             ["Token positions only", "Cross-chunk context within each chunk's embedding",
              "Index size", "Recall"], 1,
             "Embeddings reflect the surrounding context."),
            ("Contextual chunking adds cost at:",
             ["Query time", "Ingestion time (one LLM call per chunk)",
              "Both equally", "Neither"], 1,
             "Cost is paid once at ingestion."),
            ("Hierarchical retrieval returns to the LLM:",
             ["Only child chunks", "Mother chunks (parents of matched children)",
              "Random chunks", "Compressed embeddings"], 1,
             "Match child, return mother to LLM."),
        ],
        "short": [
            "Pick a corpus type and recommend a chunking strategy. Justify.",
            "Compare cost and quality of contextual vs late chunking.",
            "Sketch a hierarchical retrieval flow for a 100K-document corpus.",
        ],
    },
    4: {
        "mcq": [
            ("BM25 strengths over dense retrieval include:",
             ["Conversational queries", "Rare-term and exact matches",
              "Multimodal queries", "Multi-hop synthesis"], 1,
             "BM25 wins on exact and rare term queries."),
            ("SPLADE produces:",
             ["Dense vectors only", "Learned sparse representations",
              "Image embeddings", "Triplet stores"], 1,
             "SPLADE learns sparse representations."),
            ("Reciprocal rank fusion combines rankings via:",
             ["Mean of scores", "Sum of 1/(k + rank)",
              "Min of ranks", "Max of scores"], 1,
             "RRF formula."),
            ("Matryoshka Representation Learning trains embeddings to:",
             ["Always be 8D", "Work at multiple truncation lengths",
              "Have integer values", "Be reversible"], 1,
             "Multiple usable truncation lengths."),
            ("ColBERT scores via:",
             ["Single-vector dot product", "Sum of max query-token-to-doc-token similarities",
              "BM25 plus cosine", "Cross-encoder logits"], 1,
             "Late-interaction MaxSim."),
            ("Cross-encoders are most appropriate at:",
             ["The first stage (millions of candidates)", "The final stage (20-100 candidates)",
              "Index time", "Pre-tokenization"], 1,
             "Final reranking due to cost."),
            ("Hybrid (sparse + dense) retrieval typically:",
             ["Loses to dense alone", "Beats either alone on most corpora",
              "Wins only on images", "Has no effect"], 1,
             "Hybrid usually wins."),
            ("In the 4-stage funnel, stage 1 candidate count is roughly:",
             ["5 each", "200 each",
              "10000 each", "1 each"], 1,
             "200 each is typical first-stage breadth."),
            ("Matryoshka pruning uses what dimension first?",
             ["The full 768", "A short truncation (e.g., 64)",
              "A random dim", "Just norm"], 1,
             "Short truncation for cheap pruning."),
            ("ColBERT's PLAID engine optimizes:",
             ["Storage only", "Query latency at scale",
              "Training only", "Compression only"], 1,
             "PLAID makes ColBERT production-fast."),
            ("Cross-encoder vs bi-encoder primary difference:",
             ["Bi joins query+doc; Cross splits them",
              "Cross joins query+doc with full attention; Bi encodes independently",
              "Both are identical",
              "Cross is faster"], 1,
             "Cross fuses; bi splits."),
            ("Why use a funnel instead of cross-encoder over everything?",
             ["Cross-encoder is bad", "Cross-encoder cost is prohibitive at scale",
              "Cross-encoder requires GPU only", "Cross-encoder is rarer"], 1,
             "Cost is the binding constraint."),
        ],
        "short": [
            "Tune candidate counts per stage of the 4-stage funnel for a 1M-doc corpus with a 200ms latency budget.",
            "Pick between SPLADE and BM25 for your corpus. Justify with one experiment.",
            "When does Matryoshka give no benefit over single-stage dense?",
        ],
    },
    5: {
        "mcq": [
            ("Vision Transformers split images into:",
             ["Whole images", "16x16 patches (typically)",
              "Single pixels", "Frequency bins"], 1,
             "Patch embeddings, typically 16x16."),
            ("ViTs underperform CNNs on:",
             ["Massive datasets", "Small datasets (weaker inductive bias)",
              "Image generation", "Embeddings"], 1,
             "ViTs need scale; CNNs win small-data."),
            ("CLIP is trained with:",
             ["Cross-entropy on labels", "Contrastive loss on image-caption pairs",
              "MSE on pixels", "RL"], 1,
             "Contrastive image-text learning."),
            ("CLIP enables zero-shot classification because:",
             ["It memorizes labels", "Image and text live in a shared embedding space",
              "It is a large model", "It uses transformers"], 1,
             "Shared space allows direct comparison."),
            ("BLIP-2's Q-Former is:",
             ["A frozen LLM", "A small bridge module with learnable query tokens",
              "A diffusion model", "A vocoder"], 1,
             "Q-Former bridges frozen vision and frozen LLM."),
            ("Q-Former trainable surface relative to encoders is:",
             ["100%", "Tiny (millions of params vs billions)",
              "Identical", "More than the LLM"], 1,
             "Tiny bridge module."),
            ("CLIP struggles with:",
             ["Object presence", "Fine-grained text reading in images",
              "Common nouns", "Simple scenes"], 1,
             "Text reading and counting are weak spots."),
            ("Multimodal RAG pattern A: shared CLIP-style space; Pattern B: convert images to text. Pattern B wins when:",
             ["Image content is hard to describe", "Image content is easy to describe with text",
              "Always", "Never"], 1,
             "Text-conversion wins when descriptions are clean."),
            ("ResNet's key contribution was:",
             ["Attention", "Residual (skip) connections enabling very deep networks",
              "Batch normalization", "Tokenization"], 1,
             "Residual connections."),
            ("CLIP's training data scale was roughly:",
             ["1K pairs", "400M image-text pairs",
              "10 pairs", "10B pairs"], 1,
             "Original CLIP: 400M pairs."),
            ("BLIP-2 backbones typically include:",
             ["Only T5", "Flan-T5 or OPT depending on variant",
              "Only BERT", "Only ResNet"], 1,
             "Flan-T5 and OPT are common."),
            ("Vision-language alignment in CLIP uses:",
             ["Two losses", "A single contrastive loss aligning both modalities",
              "Cross-entropy on caption tokens", "RL from human feedback"], 1,
             "One contrastive loss across modalities."),
        ],
        "short": [
            "Sketch a multimodal RAG that retrieves images and text in one query.",
            "When does BLIP-2 beat GPT-4V on cost-quality tradeoff?",
            "Pick a domain where CLIP's text-reading weakness is a blocker. Suggest a fix.",
        ],
    },
    6: {
        "mcq": [
            ("CO-STAR's 'O' stands for:",
             ["Output", "Objective",
              "Override", "Origin"], 1,
             "Objective."),
            ("Metaprompting is:",
             ["Using GPT-2", "Asking the model to critique and improve your prompt",
              "Mass-sampling", "Adversarial prompting"], 1,
             "Self-critique loop."),
            ("Few-shot sweet spot is roughly:",
             ["1-2 examples", "3-7 diverse examples",
              "20+", "100+"], 1,
             "Three to seven."),
            ("Recency bias in few-shot means:",
             ["Earlier examples win", "Later examples are weighted more heavily",
              "Random ordering", "Equal weight"], 1,
             "Models attend more to recent examples."),
            ("Epistemic uncertainty refers to:",
             ["Random noise", "What the model does not know but could learn",
              "Tokenizer error", "Cache misses"], 1,
             "Knowledge gaps."),
            ("Calibration in LLM context means:",
             ["Color tuning", "Refusing exactly when the model does not know",
              "Quantization", "Tokenization"], 1,
             "Match confidence to correctness."),
            ("DSPy Signature defines:",
             ["The model", "Inputs and outputs of a task",
              "The tokenizer", "The retrieval store"], 1,
             "Input-output contract."),
            ("COPRO does:",
             ["Bayesian search", "Coordinate ascent on instructions",
              "Genetic mutation", "Tokenization tuning"], 1,
             "Coordinate ascent."),
            ("MIPRO is heavier than COPRO because it:",
             ["Uses different models", "Jointly optimizes instructions and demonstrations via Bayesian search",
              "Skips evaluation", "Uses more GPUs"], 1,
             "Joint Bayesian search."),
            ("GEPA uses:",
             ["Pure random search", "Evolutionary with reflective LLM critique",
              "Gradient descent on weights", "Manual editing"], 1,
             "Genetic + reflection."),
            ("TextGrad's gradients are:",
             ["Numerical", "Textual feedback from a critic LLM",
              "Image gradients", "Symbolic"], 1,
             "Text as the gradient signal."),
            ("Which is NOT a CO-STAR field?",
             ["Tone", "Audience",
              "Reward", "Style"], 2,
             "Reward is RL, not CO-STAR."),
        ],
        "short": [
            "Write a CO-STAR prompt for an internal HR Q&A bot.",
            "Compare COPRO and MIPRO on cost and gain ceiling.",
            "Sketch a calibration test for an LLM in a medical context.",
        ],
    },
    7: {
        "mcq": [
            ("Multi-hop questions are hard for vector RAG because:",
             ["Vectors are slow", "Required facts may not appear together in any single document",
              "Vectors lose entropy", "Vectors are random"], 1,
             "Multi-hop needs cross-document structure."),
            ("RAPTOR builds:",
             ["A graph database", "A hierarchical summary tree via recursive clustering",
              "A reward model", "A reranker"], 1,
             "Recursive cluster-and-summarize tree."),
            ("GraphRAG extraction uses:",
             ["Regex only", "An LLM to extract (subject, predicate, object) triplets",
              "Manual annotation only", "Random sampling"], 1,
             "LLM triplet extraction."),
            ("Entity resolution in GraphRAG addresses:",
             ["Memory", "Aliases (Apple Inc., AAPL) collapsed to canonical entities",
              "Latency", "Quantization"], 1,
             "Alias resolution prevents hairball."),
            ("Community detection (Leiden, Louvain) finds:",
             ["Random nodes", "Densely connected sub-graphs",
              "Cycles only", "Edges only"], 1,
             "Densely connected communities."),
            ("Neo4j vs Memgraph: pick Memgraph when:",
             ["Cold storage is needed", "Read-heavy in-memory workload at low latency",
              "Write-heavy disk workload", "Distributed transactions"], 1,
             "In-memory speed."),
            ("LightRAG simplifies GraphRAG by:",
             ["Adding more steps", "Skipping community detection; using dual-level retrieval",
              "Using only BM25", "Avoiding LLMs"], 1,
             "Drops community step."),
            ("RAPTOR retrieval traverses:",
             ["A flat list", "Top-down through the summary tree",
              "Bottom-up only", "Randomly"], 1,
             "Top-down traversal."),
            ("GraphRAG ingestion cost is:",
             ["Cheap", "Expensive (one LLM call per chunk for extraction)",
              "Free", "GPU-only"], 1,
             "Ingestion is LLM-heavy."),
            ("LightRAG's dual-level retrieval is:",
             ["BM25 + dense", "Local (entity neighborhood) + Global (graph-wide)",
              "Map + Reduce", "Train + Test"], 1,
             "Local + global retrieval."),
            ("RAPTOR works without:",
             ["Embeddings", "A separate graph database",
              "LLMs", "Vector stores"], 1,
             "Tree lives in vector store; no graph DB needed."),
            ("Ontology design in GraphRAG should be:",
             ["Skipped", "Defined up front with entity and relation types",
              "Learned only", "Random"], 1,
             "Up-front ontology prevents drift."),
        ],
        "short": [
            "Sketch a multi-hop question and show why vector RAG fails and GraphRAG succeeds.",
            "Compare RAPTOR and GraphRAG on ingestion cost and query latency.",
            "Pick Neo4j or Memgraph for a 100M-triplet workload and justify.",
        ],
    },
    8: {
        "mcq": [
            ("Guardrail pipeline stage order should be:",
             ["Random", "Cheap stages first, expensive last",
              "Expensive first", "Alphabetical"], 1,
             "Cheap-to-expensive for early exits."),
            ("PII detection libraries to prefer:",
             ["Hand-rolled regex", "Mature libraries like Presidio",
              "Random word lists", "ML only"], 1,
             "Use mature libraries."),
            ("Prompt injection via fetched content is mitigated by:",
             ["Trusting all sources", "Treating retrieved content as untrusted data with delimiters",
              "Disabling retrieval", "Using larger models"], 1,
             "Treat as untrusted data."),
            ("NLI verification uses what verdicts?",
             ["Yes/No", "Entailment, Contradiction, Neutral",
              "1 to 5", "0 or 1 only"], 1,
             "Three NLI labels."),
            ("DeBERTa-large-mnli is used for:",
             ["Generation", "NLI verification baseline",
              "Image classification", "Tokenization"], 1,
             "Strong NLI baseline."),
            ("Citation-based grounding asks the model to:",
             ["Hallucinate", "Cite which passage supports each claim",
              "Skip retrieval", "Use BM25"], 1,
             "Explicit citations enable verification."),
            ("P95 latency is preferred over mean because:",
             ["It's simpler", "Tail latencies determine user-perceived performance",
              "It's lower", "It's higher"], 1,
             "Users feel the tail."),
            ("Typical P95 budget for a production RAG turn:",
             ["50ms", "2-4 seconds",
              "60 seconds", "10 minutes"], 1,
             "Production RAG: a few seconds P95."),
            ("Hallucination monitoring should:",
             ["Be skipped", "Sample ~1% of traffic for offline grounding checks",
              "Sample 100%", "Run only on failure"], 1,
             "Sampling-based monitoring."),
            ("Constitutional AI is referenced because:",
             ["It's irrelevant", "Its principles inform guardrail design",
              "It's the only RAG approach", "It replaces RAG"], 1,
             "Constitutional principles map to guardrails."),
            ("Which is NOT a guardrail stage in the canonical pipeline?",
             ["Syntax", "PII",
              "Color check", "Toxicity"], 2,
             "Color check is not a guardrail."),
            ("On a 'neutral' NLI verdict, the recommended action is:",
             ["Approve silently", "Flag for review",
              "Reject all", "Retrain immediately"], 1,
             "Flag for review."),
        ],
        "short": [
            "Design a 4-stage guardrail pipeline for a healthcare RAG.",
            "Sketch a prompt-injection defense that does not block legitimate content.",
            "Allocate a 3-second P95 budget across retrieval, rerank, generation, and verification.",
        ],
    },
    9: {
        "mcq": [
            ("Derivative artifacts (factoids, QA pairs) help retrieval by:",
             ["Making the corpus smaller", "Adding alternative formulations matching real queries",
              "Quantizing the index", "Removing noise"], 1,
             "Alternative phrasings improve match rates."),
            ("HyDE generates:",
             ["A new query word", "A hypothetical answer to embed and retrieve against",
              "A reward model", "A graph"], 1,
             "Hypothesis-then-retrieve."),
            ("Multi-hop decomposition emits:",
             ["One mega-query", "Sub-queries the planner runs sequentially",
              "Random queries", "Image queries"], 1,
             "Sub-queries that compose."),
            ("Adaptive decomposition is best when:",
             ["Path is fully known up front", "Each sub-query depends on prior results",
              "All queries are identical", "Latency must be minimized"], 1,
             "Adaptive when path is unpredictable."),
            ("Semantic cache hit rates in production typically run:",
             ["0%", "20% to 40%",
              "100%", "Negative"], 1,
             "20-40% on most workloads."),
            ("Hard negative mining trains the embedder to:",
             ["Ignore negatives", "Push apart positives and similar-but-wrong documents",
              "Use only random negatives", "Skip training"], 1,
             "Hard negatives are the highest-signal training data."),
            ("Embedding fine-tuning cadence at enterprise scale is typically:",
             ["Daily", "Quarterly",
              "Never", "Decadal"], 1,
             "Quarterly cadence matches data drift."),
            ("Semantic cache threshold should be:",
             ["Random", "Tuned on a labeled set",
              "Always 0.5", "Always 1.0"], 1,
             "Threshold needs tuning."),
            ("HyDE adds what cost?",
             ["None", "One extra LLM call per query",
              "Two extra LLM calls", "GPU-only fine-tuning"], 1,
             "One LLM call up front."),
            ("Factoid generation cost is paid at:",
             ["Query time", "Ingestion time",
              "Cache eviction", "Reranking"], 1,
             "One-time ingestion cost."),
            ("Multi-hop decomposition predetermined vs adaptive: predetermined is best when:",
             ["The path is known", "The path is unpredictable",
              "There is no path", "Path is random"], 0,
             "Predetermined fits known paths."),
            ("Hard negative pool source typically includes:",
             ["Random docs", "BM25 top hits and dense top hits not labeled positive",
              "Validation set leaks", "Training labels"], 1,
             "Use retrieval results as hard negative source."),
        ],
        "short": [
            "Design a factoid-generation prompt for a legal corpus.",
            "Set a semantic cache threshold for a customer-service RAG and defend it.",
            "Sketch the hard-negative mining loop for a 1M-document corpus.",
        ],
    },
    10: {
        "mcq": [
            ("Agentic RAG differs from static RAG by:",
             ["Using more documents", "Letting the agent decide when and what to retrieve",
              "Using vector stores", "Using larger models"], 1,
             "Retrieval becomes a decision."),
            ("MCP is preferred for tool integration because it:",
             ["Is proprietary", "Standardizes tool interfaces with JSON schemas and capability negotiation",
              "Requires special hardware", "Forbids OAuth"], 1,
             "Clean abstraction."),
            ("Generalist agent with many tools wins until:",
             ["Forever", "Tool count saturates the model's selection bandwidth",
              "First retry", "GPU runs out"], 1,
             "Bandwidth limits."),
            ("Text-to-SQL schema uncertainty is addressed by:",
             ["Showing the model all tables", "Retrieving relevant tables for the question first",
              "Random sampling", "Avoiding SQL"], 1,
             "Schema retrieval step."),
            ("CTE libraries help by:",
             ["Adding complexity", "Providing pre-built reusable query patterns",
              "Replacing SQL", "Restricting databases"], 1,
             "Pre-built building blocks."),
            ("RL for SQL generation typically adds gains of:",
             ["50% accuracy", "5-15 percentage points on hard queries",
              "Negative gains", "100%"], 1,
             "Marginal but meaningful gains."),
            ("Text-to-SQL pipeline stages include:",
             ["Schema retrieval, planning, generation, verification, execution",
              "Tokenization only",
              "Image classification",
              "Pretraining"], 0,
             "Five canonical stages."),
            ("MCP capability negotiation happens:",
             ["Per call", "At session startup",
              "Never", "On failure only"], 1,
             "Session-level handshake."),
            ("Agent specialization pattern 'router' picks:",
             ["Random specialist", "The right specialist agent for the input",
              "All specialists at once", "No specialists"], 1,
             "Classifier-based routing."),
            ("SQL verification step typically:",
             ["Runs the query immediately", "Checks syntax and table/column existence before execution",
              "Skips checking", "Reformats SQL"], 1,
             "Pre-execution validation."),
            ("Agentic RAG's termination condition is:",
             ["User clicks stop", "An answer, refusal, or max-iteration cap",
              "Random", "Token count only"], 1,
             "Defined termination."),
            ("Schema retrieval embeds:",
             ["Table data", "Table descriptions and column names",
              "Query history only", "User IDs"], 1,
             "Metadata embeddings."),
        ],
        "short": [
            "Sketch an agentic RAG that beats static RAG by 10 points on multi-hop questions.",
            "Design a CTE library for a finance schema and pick 5 starter CTEs.",
            "Pick when RL helps Text-to-SQL and when SFT alone is enough.",
        ],
    },
    11: {
        "mcq": [
            ("Chinchilla recommends roughly how many tokens per parameter?",
             ["1", "5", "20", "100"], 2,
             "20 tokens per parameter."),
            ("LoRA trains:",
             ["The full base", "Only low-rank A and B matrices",
              "Embeddings only", "Layer norms"], 1,
             "Low-rank update."),
            ("Typical LoRA rank in practice:",
             ["1", "4 to 64",
              "1024", "10000"], 1,
             "4 to 64."),
            ("qLoRA quantizes the base to:",
             ["8-bit", "4-bit NF4 with double quantization",
              "2-bit", "1-bit"], 1,
             "NF4 with double quant."),
            ("RLHF pipeline order is:",
             ["RM -> SFT -> PPO", "SFT -> RM -> PPO",
              "PPO -> SFT -> RM", "RM -> PPO -> SFT"], 1,
             "SFT first, then reward model, then PPO."),
            ("RLVR replaces the reward model with:",
             ["A larger LLM", "A programmatic verifier",
              "A human judge", "Random reward"], 1,
             "Verifier as reward."),
            ("GRPO's main memory advantage comes from:",
             ["Dropping the policy", "Dropping the value network via group-relative advantage",
              "Using INT8", "Gradient checkpointing"], 1,
             "Group relative drops value head."),
            ("PPO KL penalty prevents:",
             ["Slow training", "Policy drift away from reference model",
              "Reward overflow", "Tokenizer errors"], 1,
             "KL keeps policy close."),
            ("LoRA target modules commonly include:",
             ["Layer norms only", "Q, V, O projections (and sometimes K, MLP)",
              "Tokenizer only", "Position embeddings"], 1,
             "QVO is the default."),
            ("Soft prompting trains:",
             ["Full layers", "A small trainable embedding prefix",
              "The tokenizer", "Layer norms"], 1,
             "Small prefix."),
            ("Steering vectors are applied:",
             ["During training", "At inference as activation edits",
              "To the tokenizer", "To the dataset"], 1,
             "Inference-time activation steering."),
            ("Evaluation of fine-tuned models should include:",
             ["Only target task eval", "Target task plus regression suite plus harm test",
              "No eval", "Tokenizer test only"], 1,
             "Comprehensive eval."),
        ],
        "short": [
            "Pick LoRA rank, alpha, and target modules for SQL fine-tuning on a 7B model.",
            "Sketch an RLVR setup for code generation.",
            "Compare DPO and PPO on data needs and stability.",
        ],
    },
    12: {
        "mcq": [
            ("Recall@k measures:",
             ["Top-k precision", "Fraction of all relevant retrieved in top-k",
              "Latency", "Cost"], 1,
             "Recall definition."),
            ("MRR measures:",
             ["Mean of all ranks", "Reciprocal of the rank of the first relevant",
              "Variance", "Coverage"], 1,
             "1/rank of first relevant."),
            ("NDCG earns its keep when:",
             ["Relevance is binary", "Relevance is graded",
              "There is no eval", "k=1"], 1,
             "Graded relevance with rank discount."),
            ("Ragas faithfulness measures:",
             ["Query relevance", "Whether the answer is grounded in the retrieved context",
              "Retrieval recall", "Cost"], 1,
             "Answer-context grounding."),
            ("Ragas context recall measures:",
             ["Cost", "Whether retrieved context covers what is needed for the answer",
              "Latency", "Cache hit rate"], 1,
             "Coverage of needed info."),
            ("LLM-as-judge position bias is:",
             ["A myth", "The first answer presented being judged better",
              "Tokenizer error", "GPU issue"], 1,
             "Position bias is well-documented."),
            ("LLM-as-judge verbosity bias is:",
             ["Shorter wins", "Longer is judged better",
              "Random", "Equal"], 1,
             "Verbosity bias."),
            ("RGB benchmark tests four axes; one of them is:",
             ["Color robustness", "Noise robustness",
              "Tokenizer robustness", "Index robustness"], 1,
             "Noise robustness."),
            ("Verification asymmetry means:",
             ["Both are equal", "Verification is cheaper than generation, enabling best-of-N",
              "Generation is free", "Verification is impossible"], 1,
             "Asymmetric cost enables strategies."),
            ("Self-consistency relies on:",
             ["Single sample", "Sampling N answers and voting",
              "No sampling", "Tokenizer changes"], 1,
             "Sample-and-vote."),
            ("Ragas answer relevance measures:",
             ["Whether the answer addresses the question",
              "Retrieval latency",
              "Cache size",
              "Index build time"], 0,
             "Answer-question relevance."),
            ("A good eval reports:",
             ["Mean only", "Mean and variance, with reproducible seeds",
              "Cherry-picked examples", "No numbers"], 1,
             "Mean and variance."),
        ],
        "short": [
            "Pick a task and choose between MRR, MAP, NDCG. Justify.",
            "Sketch an LLM-as-judge protocol that controls all three biases.",
            "Apply verification asymmetry to a real RAG problem you have shipped.",
        ],
    },
}
